name: Run Formula updates with check product updates [manual run]
on:
  workflow_dispatch:

jobs:
  update-formulas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'
      - name: Install uv, install requriments and run release_check.py
        run: |
          pip install uv
          uv sync
          uv run utils/release_check.py
      - name: Git commit chaged Formulas
        run: |
          git config user.name Nikitin, Alexander
          git config user.email alexander@ihumster.ru

          git add Formula/*.rb

          git commit -m "Update formula version" || true

      - name: Publish changes
        run: |
          git pull --rebase
          git push
